### ISSUE TITLE
Join request: @mohamedmehdigara

### ISSUE THREAD

**Issue by mohamedmehdigara** [flaskcwg/join-requests#3]

**Comment by Abdur-rahmaanJ** [comment]
Greetings,

We are looking for people really interested in Flask, having used Flask somewhat extensively as seen in the [criteria](https://github.com/flaskcwg/join-requests/blob/main/README.md)

With your current level in Flask, you can only volunteer for helping with events which do not require anything save some willingness ^^. You did not include your areas of volunteering btw!

**Comment by Abdur-rahmaanJ** [comment]
Closed until further notice
