### ISSUE TITLE
Join request: @vlevieux

### ISSUE THREAD

**Issue by vlevieux** [flaskcwg/join-requests#4]
Hi, I am **Victor LEVIEUX** (@vlevieux), **French** native, DevOps / System Engineer currently living in the US.

About Flask & me
============

I was introduced to Flask during my first internship 4 years ago and I became a big fan of its "micro" side and its modularity.

I occasionally answer questions about Flask on StackOverflow ([my profile](https://stackoverflow.com/users/9515831/victor)) when I have time, comment or help people (I am not a reputation farmer, just a helping hand when I can). I use it regularly at work, and also with the intention of doing a public project when my work keeps me less busy.

What and why I want to join
==================

Since I do not meet the criteria for anything more advanced yet, I offer my help for the **French translation**.

It allows me to put one's foot in the open-source. I'm both happy to help in a project that I like and if Flask can be made accessible to French speaking students (France, Canada, Belgium, Switzerland, african countries, etc...) who do not master English/Spanish/Chinese to have access to a documentation in French, it can only be a great help for them to use a web framework as easy as Flask.

I have already started a part of the translation as a proof : [Flask-fr](https://flask-fr.readthedocs.io/) ([Github Repo](https://github.com/vlevieux/flask-docs-fr))

_Obviously, my idea is to be more involved afterwards._

**Contact info:** _victor.levieux@gmail.com_

**Comment by Abdur-rahmaanJ** [comment]
Approved as french coordinator
