### ISSUE TITLE
Join Request: Event

### ISSUE THREAD

**Issue by anushkrishnav** [flaskcwg/join-requests#7]
About me
Hi, I am Anush Krishna from India
Currently, I am Undergrad student from India. 
I have experience building cool things in python for over a year and have explored various use cases and advocated flask to almost everyone I know, I might be the person that questionnaires had in mind when they ask will you recommend it to your friends in a convo.

I have Won over 10 international hackathons, hosted by colleges like Stanford, Drexel, Yale etc and Companies like MSFT have at most cases built products using flask. 

I am also a volunteer at Flask Con 21 :)

**Comment by Abdur-rahmaanJ** [comment]
Cool! You can add your profile [in here](https://github.com/flaskcwg/flaskcwg.github.io/blob/source/info.json) volunteering for events!

**Comment by Abdur-rahmaanJ** [comment]
@anushkrishnav
