### ISSUE TITLE
Join request @mmdbalkhi

### ISSUE THREAD

**Issue by mmdbalkhi** [flaskcwg/join-requests#8]
Hello. I am Komeil Parseh  I am from the Islamic Republic of Iran.

I have been working with Flask for about 2 years and I am very interested in frameworks and open source languages.

Since I am not a professional in the flask, I can translate the flask into Persian. I do not like Persian speakers to have difficulty learning the flask microframework Because they do not know English.
Footnote: I have already translated some Flask documents into Persian  ([flask-fa](https://flask-fa.readthedocs.io/) | [github](https://github.com/mmdbalkhi/flask-docs-fa))

Thanks, Komeil Parseh

**Comment by Abdur-rahmaanJ** [comment]
Greetings that's awesome! , ill approve your membership when you start the procedure.

It's very simple, see this:

https://github.com/flaskcwg/translation-coordination and this https://github.com/flaskcwg/translation-template

Any issue, ping Grey Li on the above repos

**Comment by Abdur-rahmaanJ** [comment]
Else, from what i saw you need only to translate the tutorial part

**Comment by mmdbalkhi** [comment]
Yes greyli are very helpful and helped me in a few problems.

I opened the translation issue in the [translation-coordination](https://github.com/flaskcwg/translation-coordination) a few days ago ( [Here](https://github.com/flaskcwg/translation-coordination/issues/8) )

**Comment by Abdur-rahmaanJ** [comment]
@mmdbalkhi Cool just complete those two steps then ping me

- [ ] Translate the docs/quickstart file.
- [ ] Translate the "Tutorial" part of the docs.

**Comment by mmdbalkhi** [comment]
@Abdur-rahmaanJ Hello. I'm done now, sorry if I left you waiting
