### ISSUE TITLE
Join request @MDK84

### ISSUE THREAD

**Issue by MDK84** [flaskcwg/join-requests#9]
Hello. I'm MDK and I'm a programmer.
I want to be a member of the flask-docs-fa.
I have worked with Flask and I had previously translated the flask icon into Persian and some other document files.
Thanks, MDK

**Comment by Abdur-rahmaanJ** [comment]
@MDK84 Welcome. Add yourself for volunteering to translations:  https://github.com/flaskcwg/flaskcwg.github.io/blob/0ebc089986f71381d6fffe829ac882f0af55750f/info.json#L8

**Comment by MDK84** [comment]
[#82](https://github.com/flaskcwg/flaskcwg.github.io/pull/82)
Thanks
